# Site settings
title: Twenty Thousand Leagues Under the Code
header-img: img/home-bg.png
email: mystycs@gmail.com
copyright_name: mystycs
description: > # this means to ignore newlines until "baseurl:"
  When i'm thirsty i go to the foo bar.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mystycs
learn_profile: mystycs
email_username: mystycs@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
